parserOptions:
  ecmaVersion: 6
  sourceType: module

env:
  node: true

parser: "@typescript-eslint/parser"

settings:
  import/resolver:
    typescript:
      extensions: 
        - .ts
  import/parsers:
    "@typescript-eslint/parser":
      - .ts

plugins: 
  - prettier

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript

rules:
  "sort-imports": ["error", {"allowSeparatedGroups": true, "ignoreCase": true, "ignoreDeclarationSort" : true }]
  "prettier/prettier": "error",
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-explicit-any": ["error", { ignoreRestArgs: true }]
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }]